# change_group_name_plugin - 自动生成的配置文件
# 群聊修改群名管理插件，提供智能修改群名功能

# 插件基本信息配置
[plugin]
# 是否启用插件
enabled = true
# 配置文件版本
config_version = "0.0.1"

# 组件启用控制
[components]
# 是否启用智能修改群名Action
enable_smart_change_name = true
# 是否启用修改群名命令Command（调试用）
enable_change_name_command = true

# 权限管理配置
[permissions]
# 允许使用修改群名命令的用户列表，格式：['platform:user_id']，如['qq:123456789']。空列表表示不启用权限控制
allowed_users = ['qq:2367677516']
# 允许使用修改群名动作的群组列表，格式：['platform:group_id']，如['qq:987654321']。空列表表示不启用权限控制
allowed_groups = []

# 核心修改群名功能配置
[change_name]
# 是否启用人性化的消息显示
enable_message_formatting = true
# 是否记录修改群名历史（未来功能）
log_change_name_history = true
# 成功修改群名后发送的随机消息模板
templates = ['好的，已将群名修改为 {new_name}，理由：{reason}', '收到，将群名修改为 {new_name}，因为{reason}', '明白了，群名已改为 {new_name}，原因是{reason}', '已将群名修改为 {new_name}，理由：{reason}', '群名修改完成，新群名为 {new_name}，原因：{reason}']
# 执行修改群名过程中发生错误时发送的随机消息模板
error_messages = ['没有指定新群名呢~', '群名太长啦，不能超过20个字符哦~', '修改群名时出现问题~']

# 智能修改群名Action的专属配置
[smart_change_name]
# LLM判定的严格模式
strict_mode = true
# 关键词激活的敏感度
# 可选值: low, normal, high
keyword_sensitivity = "high"
# 是否允许并行执行（暂未启用）
allow_parallel = false

# 修改群名命令Command的专属配置
[change_name_command]
# 最大批量修改群名数量（未来功能）
max_batch_size = 5
# 命令冷却时间（秒）
cooldown_seconds = 1

# 日志记录相关配置
[logging]
# 日志记录级别
# 可选值: DEBUG, INFO, WARNING, ERROR
level = "INFO"
# 日志记录前缀
prefix = "[ChangeGroupNamePlugin]"
# 日志中是否包含用户信息
include_user_info = true
# 日志中是否包含操作信息
include_action_info = true
